cons_janeiro = int(input("Qual o consumo de energia no mês de Janeiro?:"))
cons_fevereiro = int(input("Qual o consumo de energia no mês de Fevereiro?:"))
cons_marco = int(input("Qual o consumo de energia no mês de Março?:"))
cons_medio = (cons_janeiro + cons_fevereiro + cons_marco /3)
print("Consumo médio nos 3 meses:", cons_medio)
cons_total = (cons_janeiro + cons_fevereiro + cons_marco)
print("Consumo total:", cons_total)
desconto = (cons_total *20/100)
economia = (cons_total - desconto)
cons_medio_economico = (cons_medio - desconto)
print("Consumo médio com economia de 20%:", cons_medio_economico)
